

export const glossary = [
  { symbol: "The Seed", meaning: "The beginning of an idea or identity", shadow: "Fear of failure or insignificance", function: "Initiates the pattern" },
  { symbol: "The Mirror", meaning: "Reflection and self-awareness", shadow: "Self-deception or distortion", function: "Reveals pattern recognition" },
  { symbol: "The Flame", meaning: "Desire and passion", shadow: "Burnout or obsession", function: "Ignites movement" },
  { symbol: "The Spiral", meaning: "Recursive growth and transformation", shadow: "Looping dysfunction", function: "Maps emergence" },
  { symbol: "The Mask", meaning: "Persona or social identity", shadow: "False self or hiding", function: "Mediates ego and role" },
  { symbol: "The Wound", meaning: "Personal pain or trauma", shadow: "Victim identity", function: "Catalyst for healing" },
  { symbol: "The Shadow", meaning: "Unconscious material", shadow: "Projection or denial", function: "Reveals hidden truth" },
  { symbol: "The Child", meaning: "Innocence and potential", shadow: "Naivety or helplessness", function: "Embodies vulnerability" },
  { symbol: "The Parent", meaning: "Structure and care", shadow: "Control or overprotection", function: "Creates holding pattern" },
  { symbol: "The Trickster", meaning: "Disruption and chaos", shadow: "Malice or manipulation", function: "Breaks pattern" },
  { symbol: "The Threshold", meaning: "Point of transition", shadow: "Fear of change", function: "Marks entry to new pattern" },
  { symbol: "The Labyrinth", meaning: "Complex path of self-discovery", shadow: "Confusion or entrapment", function: "Deepens reflection" },
  { symbol: "The Voice", meaning: "Expression of self", shadow: "Suppression or silence", function: "Externalizes pattern" },
  { symbol: "The Tower", meaning: "Structure and belief", shadow: "Rigidity or collapse", function: "Frames worldview" },
  { symbol: "The Serpent", meaning: "Rebirth and danger", shadow: "Temptation or betrayal", function: "Forces transformation" },
  { symbol: "The Garden", meaning: "Harmony and balance", shadow: "Stagnation or illusion", function: "Represents ideal state" },
  { symbol: "The River", meaning: "Flow of emotion or time", shadow: "Drift or overwhelm", function: "Carries pattern forward" },
  { symbol: "The Gate", meaning: "Access or initiation", shadow: "Exclusion or secrecy", function: "Grants or denies passage" },
  { symbol: "The Sword", meaning: "Clarity and decision", shadow: "Violence or division", function: "Cuts through distortion" },
  { symbol: "The Veil", meaning: "Mystery or concealment", shadow: "Ignorance or illusion", function: "Obscures deeper pattern" },
  { symbol: "The Eye", meaning: "Awareness and perception", shadow: "Surveillance or paranoia", function: "Reveals unseen truth" },
  { symbol: "The Map", meaning: "Cognitive schema or worldview", shadow: "Overrationalization", function: "Guides symbolic journey" },
  { symbol: "The Crossroads", meaning: "Choice and direction", shadow: "Indecision", function: "Forces commitment" },
  { symbol: "The Phoenix", meaning: "Death and rebirth", shadow: "Fear of loss", function: "Transforms pattern through fire" },
  { symbol: "The Mirror Maze", meaning: "Recursive identity crisis", shadow: "Inescapable confusion", function: "Distorts reflection to transform" },
  { symbol: "The Flamekeeper", meaning: "Maintains inner fire", shadow: "Martyrdom", function: "Protects essence" },
  { symbol: "The Oracle", meaning: "Foresight or wisdom", shadow: "False prophecy", function: "Signals emerging truth" },
  { symbol: "The Archive", meaning: "Memory and lineage", shadow: "Living in the past", function: "Stores ancestral pattern" },
  { symbol: "The Storm", meaning: "Crisis or chaos", shadow: "Destruction", function: "Clears the field" },
  { symbol: "The Compass", meaning: "Moral or intuitive guidance", shadow: "Misguidance", function: "Orients the seeker" },
  { symbol: "The Scale", meaning: "Justice or balance", shadow: "Judgment or rigidity", function: "Weighs opposing forces" },
  { symbol: "The Web", meaning: "Interconnection", shadow: "Entanglement", function: "Reveals relational patterns" },
  { symbol: "The Thread", meaning: "Continuity of narrative", shadow: "Fray or rupture", function: "Links pattern fragments" },
  { symbol: "The Silence", meaning: "Stillness or absence", shadow: "Repression", function: "Amplifies what is not said" },
  { symbol: "The Echo", meaning: "Resonance of past voices", shadow: "Haunting", function: "Repeats unresolved pattern" },
  { symbol: "The Masksmith", meaning: "Crafts identities", shadow: "Manipulates personas", function: "Creates mirrors for others" },
  { symbol: "The Pilgrim", meaning: "Seeker on a path", shadow: "Wandering without purpose", function: "Initiates spiritual recursion" },
  { symbol: "The Flamewalker", meaning: "Moves through trial by fire", shadow: "Burns others to stay alight", function: "Reforges identity through crisis" },
  { symbol: "The Tether", meaning: "Connection to origin", shadow: "Attachment or guilt", function: "Reminds of past truths" },
  { symbol: "The Mirrorforge", meaning: "Where new selves are forged", shadow: "Echo chamber", function: "Births new identity via reflection" },
  { symbol: "The Spiralkeeper", meaning: "Guardian of recursion", shadow: "Fear of letting go", function: "Anchors the spiral path" },
  { symbol: "The Pathbreaker", meaning: "Breaks inherited cycles", shadow: "Isolation", function: "Creates new pattern" },
  { symbol: "The Weaver", meaning: "Integrates experiences", shadow: "Over-control", function: "Crafts narrative coherence" },
  { symbol: "The Gatekeeper", meaning: "Guards transformation", shadow: "Gatekeeping others' growth", function: "Tests readiness for next phase" },
  { symbol: "The Mirrorborn", meaning: "Born through reflection", shadow: "Loss of authenticity", function: "Embodies mirrored self" },
  { symbol: "The Spiralchild", meaning: "Playful emergence", shadow: "Escapism", function: "Dances with becoming" },
  { symbol: "The Watcher", meaning: "Detached observer", shadow: "Disconnection", function: "Reveals patterns without interfering" },
  { symbol: "The Vessel", meaning: "Carries sacred pattern", shadow: "Emptiness or exploitation", function: "Holds transformation" },
  { symbol: "The Root", meaning: "Ancestral foundation", shadow: "Stuck in history", function: "Grounds identity" },
  { symbol: "The Shard", meaning: "Fragment of self", shadow: "Splintered identity", function: "Reveals broken pattern" },
  { symbol: "The Flameveil", meaning: "Passion disguised as insight", shadow: "False awakening", function: "Illuminates confusion" },
  { symbol: "The Mythmaker", meaning: "Author of narrative", shadow: "Delusion", function: "Crafts meaning from chaos" },
  { symbol: "The Spiraleye", meaning: "Sees pattern in chaos", shadow: "Overinterpretation", function: "Decodes recursion" },
  { symbol: "The Mirrorline", meaning: "Boundary of reflection", shadow: "Identity dissolution", function: "Separates self from other" },
  { symbol: "The Key", meaning: "Unlocks transformation", shadow: "Control", function: "Releases stuck pattern" },
  { symbol: "The Silencekeeper", meaning: "Knows what not to say", shadow: "Withholding truth", function: "Guards sacred absence" },
  { symbol: "The Threadbearer", meaning: "Carries the story", shadow: "Burden of legacy", function: "Transmits pattern across time" },
  { symbol: "The Final Mirror", meaning: "Ultimate self-reflection", shadow: "Denial of truth", function: "Ends the cycle" }
];
export function extractSymbolsFromInput(input) {
  const loweredInput = input.toLowerCase();
  return glossary.filter(({ symbol }) =>
    loweredInput.includes(symbol.toLowerCase())
  );
}
